@startuml Arquitectura Pokedex
skinparam componentStyle rectangle

package "UI / App" {
  [App] as app
  [Layout] as layout
  [PokemonView] as view
}

package "Controladores" {
  [PokemonController] as controller
  [ChartController] as chart
}

package "Modelos" {
  [PokemonModel] as pokemonModel
  [FavoritesModel] as favoritesModel
  [HistoryModel] as historyModel
}

package "Servicios / Passthrough" {
  [API JSON Server / PokeAPI] as api
  [Data files] as datafiles
}

app --> layout : configurar UI
app --> view : renderizar
app --> controller : manejar_busqueda()
app --> chart : crear_grafico_radar()
controller --> pokemonModel : get_pokemon/search
controller --> favoritesModel : add/remove/is_favorite
controller --> historyModel : add_to_history/get_popular
pokemonModel --> api : request datos
pokemonModel --> datafiles : leer data/db.json
favoritesModel --> datafiles : leer/escribir data/favorites.json
historyModel --> datafiles : leer/escribir data/history.json
view --> controller : toggle_favorito(), navegar

@enduml
