@startuml Estado App Pokedex
[*] --> Iniciando
Iniciando --> Idle : app_cargada
Idle : estado = Espera input
Idle --> BusquedaEnCurso : usuario_busca
BusquedaEnCurso : estado = Cargando datos
BusquedaEnCurso --> ResultadosDisponibles : pokemon_encontrado
BusquedaEnCurso --> ErrorBusqueda : no_encontrado / falla_api
ResultadosDisponibles : estado = Mostrar lista y tarjeta
ResultadosDisponibles --> DetallePokemon : seleccionar_pokemon
ResultadosDisponibles --> Idle : nueva_busqueda
DetallePokemon : estado = Ver detalles
DetallePokemon --> ResultadosDisponibles : volver_lista
ErrorBusqueda : estado = Mostrar error
ErrorBusqueda --> Idle : reintentar
@enduml