@startuml
left to right direction
actor "Usuario" as User
rectangle "Buscar Pokémon" {
  usecase "Ingresar nombre/ID" as UC
  usecase "Validar entrada" as UC2
  usecase "Buscar en DB local" as UC3
  usecase "Fallback PokéAPI" as UC4
  usecase "Mostrar resultados" as UC5
}
User --> UC
User --> UC5
UC -> UC2
UC2 --> UC3
UC3 --> UC4 : si no encuentra
UC3 --> UC5 : si encuentra
UC4 --> UC5
@enduml