@startuml
left to right direction
actor "Sistema" as System
rectangle "Cargar datos JSON local" {
  usecase "Leer data/db.json" as UC1
  usecase "Parsear JSON" as UC2
  usecase "Retornar lista de pokémon" as UC3
}
System --> UC1
UC1 --> UC2
UC2 --> UC3
@enduml