@startuml
left to right direction
actor "Sistema" as System
actor "Usuario" as User
rectangle "Actualizar datos desde PokéAPI" {
  usecase "Iniciar actualización" as UC1
  usecase "Consultar PokéAPI" as UC2
  usecase "Actualizar data/db.json" as UC3
  usecase "Confirmar actualización" as UC4
}
User --> UC1
UC1 --> UC2
UC2 --> UC3
UC3 --> UC4
@enduml