@startuml ConsultarOfertaAcademica
left to right direction
actor Estudiante

rectangle "Sistema de Matrículas" {
    
    usecase "Autenticarse en el sistema" as UC1
    usecase "Consultar oferta académica" as UC2
    usecase "Mostrar mensaje:\nsin materias abiertas" as UC3

    ' Control de posición visual
    UC1 -[hidden]-> UC2
    UC2 -[hidden]-> UC3
}

Estudiante --> UC2
UC2 .> UC3 : <<extend>>
UC2 .> UC1 : <<include>>
@enduml

